### ISSUE TITLE
Many errors

### ISSUE THREAD

**Issue by leftbezero** [GSRHackZ/Google-Meet-Attendance-Bot-Code-Executor#1]
1. It does not work at all, I tried many times changing the time and others changes, but the bot did not work
2. This link https://gsrhackz.github.io/Google-Meet-Attendance-Bot/ only works in chrome, it does not work in Firefox because when you click on save settings, it does not show the meeting and time space, just "work" in chrome, when I write the word "work"  it means that it shows the whole options that you mentioned, but the bot does not work
3. On tamper monkey description the first link is wrong, it does not redirect to the right page

waste of time

**Comment by GSRHackZ** [comment]
These issues have been fixed.
